development: &default
  adapter: postgresql
  host: localhost
  username: postgres
  password: password

development:
  <<: *default
  database: elloperations-dev

test:
  <<: *default
  database: elloperations-test

production:
  <<: *default
  database: elloperations-production
